apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-user-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-user-pod
  namespaceSelector:
    matchNames:
      - default   # <-- syntaxe correcte
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
