apiVersion: v1
kind: Service
metadata:
  name: backend-user-service
spec:
  selector:
    app: backend-user-pod
  ports:
    - name: http
      port: 5000
      targetPort: 5000
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
